version: '3'

tasks:
  default:
    desc: show commands
    cmds:
      - task -l --sort none
  fmt:
    desc: terraform fmt
    dir: terraform
    cmds:
      - terraform fmt
  plan:
    desc: terraform plan
    dir: terraform
    cmds:
      - terraform plan
  apply:
    desc: terraform apply
    dir: terraform
    cmds:
      - terraform apply
  destroy:
    desc: terraform destroy
    dir: terraform
    cmds:
      - terraform destroy
  rmsec:
    desc: remove secrets value from secrets manager
    cmds:
      - aws secretsmanager delete-secret --secret-id sbcntr/mysql --force-delete-without-recovery
      - aws secretsmanager describe-secret --secret-id sbcntr/mysql
  list:
    desc: terraform state list
    dir: terraform
    cmds:
      - terraform state list
  rmecr:
    desc: remove ecr and s3_bucket from terraform state file
    dir: terraform
    cmds:
      - terraform state rm aws_ecr_repository.sbcntr-frontend || true
      - terraform state rm aws_ecr_repository.sbcntr-backend || true
      - terraform state rm aws_ecr_repository.sbcntr-base || true
      - terraform state rm aws_s3_bucket.sbcntr-codepipeline-bucket || true
  impecr:
    desc: import ecr to terraform state file
    dir: terraform
    cmds:
      - terraform import aws_ecr_repository.sbcntr-frontend sbcntr-frontend || true
      - terraform import aws_ecr_repository.sbcntr-backend sbcntr-backend || true
      - terraform import aws_ecr_repository.sbcntr-base sbcntr-base || true
  appecr:
    desc: terraform apply for ecr
    dir: terraform
    cmds:
      - terraform apply --target=aws_ecr_repository.sbcntr-frontend --target=aws_ecr_repository.sbcntr-backend --target=aws_ecr_repository.sbcntr-base || true
      - terraform apply --target=aws_ecr_lifecycle_policy.sbcntr-frontend --target=aws_ecr_lifecycle_policy.sbcntr-frontend --target=aws_ecr_lifecycle_policy.sbcntr-backend --target=aws_ecr_lifecycle_policy.sbcntr-base || true
  inframap:
    desc: generate image by inframap
    dir: terraform
    cmds:
      - inframap generate . | dot -Tpng > inframap_generate.png
  pluralith:
    desc: generate image by pluralith
    dir: terraform
    cmds:
      - pluralith graph
  