version: '3'

tasks:
  default:
    desc: show commands
    cmds:
      - task -l --sort none
  plan:
    desc: terraform plan
    dir: terraform
    cmds:
      - terraform plan
  apply:
    desc: terraform apply
    dir: terraform
    cmds:
      - terraform apply
  destroy:
    desc: terraform destroy
    dir: terraform
    cmds:
      - terraform destroy
